# Site
name: 'Park Jin-A'
description: 'Just For Fun'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/'
disqus: 'https-github-com-goguma1111-my-coding-test'
email: 'doffltm112543@gmail.com'
mailchimp-list: 'https-github-com-goguma1111-my-coding-test'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           Park Jin-A
      site:           https://github.com/Goguma1111
      avatar:         ./assets/images/프로필.jpg
      bio:            "Just For Fun"
      email:          doffltm112543@gmail.com
      #twitter:       https://twitter.com/wowthemesnet

 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: goguma
      avatar: ./assets/images/프로필.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]